[workspace]
members = [
    "dictmacro",
    "word",
]

[package]
name = "jpn101util"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dictmacro = {path="dictmacro"}
word = {path="word"}