[package]
name = "dictmacro"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro=true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
word = {path="../word"}
syn="1.0.82"
quote = "1.0.10"
proc-macro2 = "1.0.32"