use word::{StaticConjugation, StaticWordType};

use crate::*;

pub const WORDS: &'static [StaticWordType] = &[
    noun!(1, "あのう （anoo）", "um..."),
    noun!(1, "いま (ima)", "now"),
    noun!(1, "えいご (eego)", "English (language)"),
    noun!(1, "ええ/はい (ee) (hai)", "yes"),
    noun!(1, "がくせい (gakusee)", "student"),
    noun!(1, "～ご (go)", "language"),
    noun!(1, "こうこう (kookoo)", "high school"),
    noun!(1, "ごご (gogo)", "P.M. (afternoon)"),
    noun!(1, "ごぜん (gozen)", "A.M. (morning)"),
    noun!(1, "～さい (sai)", "years old (counter)"),
    noun!(1, "～さん (～san)", "Mr./Ms."),
    noun!(1, "～じ (...ji)", "o'clock"),
    noun!(1, "いちじ (ichiji)", "one o'clock"),
    noun!(1, "～じん (jin)", "～people (nationality)"),
    noun!(1, "にほんじん (nihonjin)", "Japanese people"),
    noun!(1, "せんこう (senkoo)", "major (in a subject at college)"),
    noun!(1, "せんせい (sensee)", "teacher/professor"),
    noun!(1, "そうです (soo desu)", "That's right."),
    noun!(1, "そうですか (soo desu ka)", "I see; Is that so?"),
    noun!(1, "だいがく (daigaku)", "college, university"),
    noun!(1, "でんわ (denwa)", "telephone"),
    noun!(1, "ともだち (tomodachi)", "friend"),
    noun!(1, "なまえ (namae)", "name"),
    noun!(1, "なん/なに (nan/nani)", "what"),
    noun!(1, "なんじ (nanji)", "what time?"),
    noun!(1, "なんさい (nansai)", "how old"),
    noun!(1, "なんねんせい (nannensee)", "what year? (in school)"),
    noun!(1, "にほん (nihon)", "Japan"),
    noun!(1, "～ねんせい (...nensee)", "...year student"),
    noun!(1, "いちねんせい (Ichi nen see)", "first-year student"),
    noun!(1, "はん (han)", "half"),
    noun!(1, "にじはん (nijihan)", "half past two"),
    noun!(1, "ばんごう (bangoo)", "number"),
    noun!(
        1,
        "りゅうがくせい (ryuugakusee)",
        "exchange/international student"
    ),
    noun!(1, "わたし (watashi)", "I (used by anyone)"),
    noun!(1, "アメリカ (あめりか) (amerika)", "America/US"),
    noun!(1, "イギリス （いぎりす) (igirisu)", "Britain"),
    noun!(
        1,
        "オーストラリア （おうすとらりあ）(Oosutoraria)",
        "Australia"
    ),
    noun!(1, "カナダ （かなだ) (kanada)", "Canada"),
    noun!(1, "かんこく (kankoku)", "South Korea"),
    noun!(1, "ちゅうごく (Chuugoku)", "China"),
    noun!(1, "インド （いんど) (indo)", "India"),
    noun!(1, "エジプト （えじぷと)(ejiputo)", "Egypt"),
    noun!(1, "フィリピン (ふぃりぴん) (firipin)", "Philippines"),
    noun!(1, "かがく (kagaku)", "science/chemistry"),
    noun!(1, "せいぶつがく (seebutsugaku)", "biology"),
    noun!(1, "アジアけんきゅう (あじあ/Ajia kenkyuu)", "Asian studies"),
    noun!(1, "こうがく (koogaku)", "engineering"),
    noun!(1, "けいざい (keezai)", "economics"),
    noun!(
        1,
        "こくさいかんけい (kokusaikankee)",
        "international relations"
    ),
    noun!(
        1,
        "コンピューター (こんぴゅうたあ) (konpyuutaa)",
        "computer"
    ),
    noun!(1, "じんるいがく (jinruigaku)", "anthropology"),
    noun!(1, "せいじ (seeji)", "politics"),
    noun!(1, "ビジネス (びじねす) (bijinesu)", "business"),
    noun!(1, "ぶんがく (bungaku)", "literature"),
    noun!(1, "れきし (rekishi)", "history"),
    noun!(1, "いしゃ (isha)", "doctor"),
    noun!(1, "かんごし (kangoshi)", "nurse"),
    noun!(1, "かいしゃいん (kaishain)", "office worker"),
    noun!(1, "こうこうせい (kookoosee)", "high school student"),
    noun!(1, "しゅふ (shufu)", "housewife"),
    noun!(1, "だいがくいんせい (daigakuinsee)", "graduate student"),
    noun!(1, "だいがくせい (daigakusee)", "college student"),
    noun!(1, "べんごし (bengoshi)", "lawyer"),
    noun!(1, "おかあさん (okaasan)", "mother"),
    noun!(1, "おとうさん (otoosan)", "father"),
    noun!(1, "おねえさん (oneesan)", "older sister"),
    noun!(1, "おにいさん (oniisan)", "older brother"),
    noun!(1, "いもうと (imooto)", "younger sister"),
    noun!(1, "おとうと (otooto)", "younger brother"),
    noun!(2, "これ (kore)", "this one"),
    noun!(2, "それ (sore)", "that one"),
    noun!(2, "あれ (are)", "that one over there"),
    noun!(2, "どれ (dore)", "which one"),
    noun!(2, "この (kono)", "this"),
    noun!(2, "その (sono)", "that"),
    noun!(2, "あの (ano)", "that (over there)"),
    noun!(2, "どの (dono)", "which"),
    noun!(2, "ここ (koko)", "here"),
    noun!(2, "そこ (soko)", "there"),
    noun!(2, "あそこ (asoko)", "that place over there"),
    noun!(2, "どこ (doko)", "where"),
    noun!(2, "だれ (dare)", "who"),
    noun!(2, "おいしい (oishii)", "delicious, tasty"),
    noun!(2, "さかな (sakana)", "fish"),
    noun!(2, "とんかつ (tonkatsu)", "pork cutlet"),
    noun!(2, "にく (niku)", "meat"),
    noun!(2, "メニュー（めんにゅう) (menyuu)", "menu"),
    noun!(2, "やさい (yasai)", "vegetable"),
    noun!(2, "かさ (kasa)", "umbrella"),
    noun!(2, "かばん (kaban)", "bag"),
    noun!(2, "くつ (kutsu)", "shoes"),
    noun!(2, "さいふ (saifu)", "wallet"),
    noun!(2, "ジーンズ （じいんず）(jiinzu)", "jeans"),
    noun!(2, "じしょ (jisho)", "dictionary"),
    noun!(2, "じてんしゃ (jitensha)", "bicycle"),
    noun!(2, "しんぶん (shinbun)", "newspaper"),
    noun!(2, "スマホ (すまほ) (sumaho)", "smartphone; mobile"),
    noun!(2, "Tシャツ （Tしゃつ）(T-shatsu）", "T-shirt"),
    noun!(2, "とけい (tokee)", "watch/clock"),
    noun!(2, "ノート （のうと）(nooto)", "notebook"),
    noun!(2, "ペン （ぺん）(pen)", "pen"),
    noun!(2, "ぼうし (booshi)", "hat, cap"),
    noun!(2, "ほん (hon)", "book"),
    noun!(2, "ぎんこう (ginkoo)", "bank"),
    noun!(2, "コンビニ (こんびに) (konbini)", "convenience store"),
    noun!(2, "トイレ （といれ）(toire)", "toilet, restroom"),
    noun!(2, "としょかん (toshokan)", "library"),
    noun!(2, "ゆうびんきょく (yuubinkyoku)", "post office"),
    noun!(2, "イギリス （いぎりす）(igirisu)", "Britain"),
    noun!(2, "かんこく (kankoku)", "South Korea"),
    noun!(2, "ちゅうごく (chuugoku)", "China"),
    noun!(2, "えいご (eigo)", "English (language)"),
    noun!(2, "けいざい (keezai)", "economics"),
    noun!(
        2,
        "コンピューター （こんぴゅうたあ）(konpyuutaa)",
        "computer"
    ),
    noun!(2, "ビジネス （びじねす）(bijinesu)", "business"),
    noun!(2, "れきし (rekishi)", "history"),
    noun!(2, "おかあさん (okaasan)", "mother"),
    noun!(2, "おとうさん (otoosan)", "father"),
    noun!(2, "いくら (ikura)", "how much"),
    noun!(2, "～えん (～en)", "yen"),
    noun!(2, "たかい (takai)", "expensive; high"),
    noun!(
        2,
        "いらっしゃいませ (irasshaimase)",
        "Welcome (to our store)"
    ),
    noun!(2, "（～を）おねがいします (...o onegaishimasu)", "please"),
    noun!(2, "（～を）ください (...o kudasai)", "Please give me..."),
    noun!(2, "じゃあ (jaa)", "then...; if that is the case,..."),
    noun!(2, "どうぞ (doozo)", "Please.; Here it is."),
    noun!(2, "どうも (doomo)", "thank you"),
    noun!(3, "えいが", "movie", "映画"),
    noun!(3, "おんがく", "music", "音楽"),
    noun!(3, "ざっし", "magazine", "雑誌"),
    noun!(3, "スポーツ", "sports"),
    noun!(3, "デート", "date (romantic, not calendar)"),
    noun!(3, "テニス", "tennis"),
    noun!(3, "テレビ", "television"),
    noun!(3, "アイスクリーム", "ice cream"),
    noun!(3, "ハンバーガー", "hamburger"),
    noun!(3, "おさけ", "sake; alcohol", "お酒"),
    noun!(3, "おちゃ", "green tea", "お茶"),
    noun!(3, "コーヒー", "coffee"),
    noun!(3, "みず", "water", "水"),
    noun!(3, "あさごはん", "breakfast", "朝ご飯"),
    noun!(3, "ひるごはん", "lunch", "昼ご飯"),
    noun!(3, "ばんごはん", "dinner", "晩ご飯"),
    noun!(3, "いえ", "house", "家"),
    noun!(3, "うち", "home; my place"),
    noun!(3, "がっこう", "school", "学校"),
    noun!(3, "カフェ", "cafe"),
    noun!(3, "あさ", "morning", "朝"),
    noun!(3, "あした", "tomorrow", "明日"),
    noun!(3, "いつ", "when"),
    noun!(3, "きょう", "today", "今日"),
    noun!(3, "～ごろ", "at about (time)"),
    noun!(3, "こんばん", "tonight", "今晩"),
    noun!(3, "しゅうまつ", "weekend", "週末"),
    noun!(3, "どようび", "Saturday", "土曜日"),
    noun!(3, "にちようび", "Sunday", "日曜日"),
    noun!(3, "まいにち", "every day", "毎日"),
    noun!(3, "まいばん", "every night", "毎晩"),
    uverb!(3, "いく", "to go", "行く"),
    uverb!(3, "かえる", "go home, return", "帰る"),
    uverb!(3, "きく", "to listen, hear", "聞く"),
    uverb!(3, "のむ", "to drink", "飲む"),
    uverb!(3, "はなす", "to speak, to talk", "話す"),
    uverb!(3, "よむ", "to read", "読む"),
    ruverb!(3, "おきる", "get up, wake up", "起きる"),
    ruverb!(3, "たべる", "to eat", "食べる"),
    ruverb!(3, "ねる", "to sleep; to go to sleep", "寝る"),
    ruverb!(3, "みる", "to see; to look at; to watch", "見る"),
    StaticWordType::Verb {
        word: static_word!(3, "くる", "to come", "来る"),
        conjugation: StaticConjugation {
            present_affirmative: "きます",
            present_negative: "しません",
            past_affirmative: "きました",
            past_negative: "きませんでした",
        },
    },
    StaticWordType::Verb {
        word: static_word!(3, "する", "to do"),
        conjugation: StaticConjugation {
            present_affirmative: "きます",
            present_negative: "しません",
            past_affirmative: "きました",
            past_negative: "きませんでした",
        },
    },
    StaticWordType::Verb {
        word: static_word!(3, "べんきょうする", "to study", "勉強する"),
        conjugation: StaticConjugation {
            present_affirmative: "べんきょうします",
            present_negative: "べんきょうしません",
            past_affirmative: "べんきょうしました",
            past_negative: "べんきょうしませんでした",
        },
    },
    StaticWordType::Adjective {
        word: static_word!(3, "いい", "good"),
        conjugation: StaticConjugation {
            present_affirmative: "いいです",
            present_negative: "よくないです",
            past_affirmative: "よかった",
            past_negative: "よくなかった",
        },
    },
    iadjective!(3, "はやい", "early", "早い"),
    noun!(3, "あまり + negative", "not much"),
    noun!(3, "ぜんぜん", "not at all", "全然"),
    noun!(3, "たいてい", "usually, mostly"),
    noun!(3, "ちょっと", "a little"),
    noun!(3, "ときどき", "sometimes", "時々"),
    noun!(3, "よく", "often; much"),
    noun!(3, "そうですね", "That's right.; Let me see."),
    noun!(3, "でも", "but"),
    noun!(3, "どうですか", "How about...?; How is...?"),
    noun!(3, "ええ", "yes"),
];
